import type { Metadata } from "next";
import "./globals.css";
import { LocaleProvider } from "@/context/localeContext";
import Template from "./template";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
  test,
  test1,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
  test: React.ReactNode;
  test1: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LocaleProvider>
          <main>{children}</main>
        </LocaleProvider>
        <div id="modal-root" />
      </body>
    </html>
  );
}
